version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclusions:
    generated: strict
