version: 2

project_name: gomap

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gomap
    main: .
    binary: gomap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X github.com/NexusFireMan/gomap/cmd/gomap.Version={{.Version}}
      - -X github.com/NexusFireMan/gomap/cmd/gomap.Commit={{.Commit}}
      - -X github.com/NexusFireMan/gomap/cmd/gomap.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
  make_latest: true
